"""
Django settings for vehicle project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# ───────────────────────────────────────────────────────────────────────────────
# Security / Environment
# ───────────────────────────────────────────────────────────────────────────────
# Keep your real secret key in an environment variable in production.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure--im5k6e2#od752&guoi=jp+yjk!nho9@^!55jn(e0t%shp81*e",
)

# DEBUG from env; default False on Render, True locally if you want.
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",   # Render apps
]

# Required so POSTs from your Render domain pass CSRF checks
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]

# ───────────────────────────────────────────────────────────────────────────────
# Applications
# ───────────────────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "vehiapp",
    "widget_tweaks",
]

# ───────────────────────────────────────────────────────────────────────────────
# Middleware (WhiteNoise right after SecurityMiddleware)
# ───────────────────────────────────────────────────────────────────────────────
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # serve static files on Render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vehicle.urls"

# ───────────────────────────────────────────────────────────────────────────────
# Templates
# ───────────────────────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-level templates folder; keep it or remove if unused
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vehicle.wsgi.application"

# ───────────────────────────────────────────────────────────────────────────────
# Database (SQLite is fine for demo; for production, consider Postgres)
# ───────────────────────────────────────────────────────────────────────────────
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ───────────────────────────────────────────────────────────────────────────────
# Password validation
# ───────────────────────────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ───────────────────────────────────────────────────────────────────────────────
# Internationalization
# ───────────────────────────────────────────────────────────────────────────────
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ───────────────────────────────────────────────────────────────────────────────
# Static files / WhiteNoise
# ───────────────────────────────────────────────────────────────────────────────
STATIC_URL = "/static/"

# Where collectstatic puts files (Render requires this!)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Only include project-level static folder if it exists (prevents warnings on Render)
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# WhiteNoise storage with hashed filenames + compression
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ───────────────────────────────────────────────────────────────────────────────
# Default primary key field type
# ───────────────────────────────────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ───────────────────────────────────────────────────────────────────────────────
# Auth redirects
# ───────────────────────────────────────────────────────────────────────────────
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_REDIRECT_URL = "/admin/dashboard/"

# ───────────────────────────────────────────────────────────────────────────────
# Email (dev)
# ───────────────────────────────────────────────────────────────────────────────
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# ───────────────────────────────────────────────────────────────────────────────
# Security hints when running behind a proxy (Render)
# ───────────────────────────────────────────────────────────────────────────────
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
